package cn.itcast.zjw.mybatis.pojo;

import java.io.Serializable;
import java.util.Date;

public class Orders implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.ID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.USERID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.ORDERSNUMBER
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private Integer ordersnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.CREATETIME
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERS.NOTE
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.ID
     *
     * @return the value of ORDERS.ID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.ID
     *
     * @param id the value for ORDERS.ID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.USERID
     *
     * @return the value of ORDERS.USERID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.USERID
     *
     * @param userid the value for ORDERS.USERID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.ORDERSNUMBER
     *
     * @return the value of ORDERS.ORDERSNUMBER
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public Integer getOrdersnumber() {
        return ordersnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.ORDERSNUMBER
     *
     * @param ordersnumber the value for ORDERS.ORDERSNUMBER
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setOrdersnumber(Integer ordersnumber) {
        this.ordersnumber = ordersnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.CREATETIME
     *
     * @return the value of ORDERS.CREATETIME
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.CREATETIME
     *
     * @param createtime the value for ORDERS.CREATETIME
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERS.NOTE
     *
     * @return the value of ORDERS.NOTE
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERS.NOTE
     *
     * @param note the value for ORDERS.NOTE
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}