package cn.itcast.zjw.shiro.po;

public class SysPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.id
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.name
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.type
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.url
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.percode
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    private String percode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.parentid
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.parentids
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    private String parentids;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.sortstring
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    private String sortstring;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.available
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    private String available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.id
     *
     * @return the value of sys_permission.id
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.id
     *
     * @param id the value for sys_permission.id
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.name
     *
     * @return the value of sys_permission.name
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.name
     *
     * @param name the value for sys_permission.name
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.type
     *
     * @return the value of sys_permission.type
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.type
     *
     * @param type the value for sys_permission.type
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.url
     *
     * @return the value of sys_permission.url
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.url
     *
     * @param url the value for sys_permission.url
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.percode
     *
     * @return the value of sys_permission.percode
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public String getPercode() {
        return percode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.percode
     *
     * @param percode the value for sys_permission.percode
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public void setPercode(String percode) {
        this.percode = percode == null ? null : percode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.parentid
     *
     * @return the value of sys_permission.parentid
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.parentid
     *
     * @param parentid the value for sys_permission.parentid
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.parentids
     *
     * @return the value of sys_permission.parentids
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public String getParentids() {
        return parentids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.parentids
     *
     * @param parentids the value for sys_permission.parentids
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public void setParentids(String parentids) {
        this.parentids = parentids == null ? null : parentids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.sortstring
     *
     * @return the value of sys_permission.sortstring
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public String getSortstring() {
        return sortstring;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.sortstring
     *
     * @param sortstring the value for sys_permission.sortstring
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public void setSortstring(String sortstring) {
        this.sortstring = sortstring == null ? null : sortstring.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.available
     *
     * @return the value of sys_permission.available
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public String getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.available
     *
     * @param available the value for sys_permission.available
     *
     * @mbggenerated Wed Jun 29 21:33:43 GMT+08:00 2016
     */
    public void setAvailable(String available) {
        this.available = available == null ? null : available.trim();
    }
}