package cn.itcast.zjw.project.domain;

public class Orderdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.id
     *
     * @mbggenerated Thu Dec 31 17:41:44 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.order_id
     *
     * @mbggenerated Thu Dec 31 17:41:44 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.items_id
     *
     * @mbggenerated Thu Dec 31 17:41:44 CST 2015
     */
    private Integer itemsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetail.items_number
     *
     * @mbggenerated Thu Dec 31 17:41:44 CST 2015
     */
    private Integer itemsNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.id
     *
     * @return the value of orderdetail.id
     *
     * @mbggenerated Thu Dec 31 17:41:44 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.id
     *
     * @param id the value for orderdetail.id
     *
     * @mbggenerated Thu Dec 31 17:41:44 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.order_id
     *
     * @return the value of orderdetail.order_id
     *
     * @mbggenerated Thu Dec 31 17:41:44 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.order_id
     *
     * @param orderId the value for orderdetail.order_id
     *
     * @mbggenerated Thu Dec 31 17:41:44 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.items_id
     *
     * @return the value of orderdetail.items_id
     *
     * @mbggenerated Thu Dec 31 17:41:44 CST 2015
     */
    public Integer getItemsId() {
        return itemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.items_id
     *
     * @param itemsId the value for orderdetail.items_id
     *
     * @mbggenerated Thu Dec 31 17:41:44 CST 2015
     */
    public void setItemsId(Integer itemsId) {
        this.itemsId = itemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetail.items_number
     *
     * @return the value of orderdetail.items_number
     *
     * @mbggenerated Thu Dec 31 17:41:44 CST 2015
     */
    public Integer getItemsNumber() {
        return itemsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetail.items_number
     *
     * @param itemsNumber the value for orderdetail.items_number
     *
     * @mbggenerated Thu Dec 31 17:41:44 CST 2015
     */
    public void setItemsNumber(Integer itemsNumber) {
        this.itemsNumber = itemsNumber;
    }
}