package cn.itcast.zjw.dao;

import cn.itcast.zjw.po.Orderdetail;
import cn.itcast.zjw.po.OrderdetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    int countByExample(OrderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    int deleteByExample(OrderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    int insert(Orderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    int insertSelective(Orderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    List<Orderdetail> selectByExample(OrderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") Orderdetail record, @Param("example") OrderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    int updateByExample(@Param("record") Orderdetail record, @Param("example") OrderdetailExample example);
}