package cn.itcast.zjw.po;

import java.math.BigDecimal;

public class Orderdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERDETAIL.ID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERDETAIL.ORDERSID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private BigDecimal ordersid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERDETAIL.ITEMSID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private BigDecimal itemsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERDETAIL.ITEMSNUM
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private BigDecimal itemsnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERDETAIL.ID
     *
     * @return the value of ORDERDETAIL.ID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERDETAIL.ID
     *
     * @param id the value for ORDERDETAIL.ID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERDETAIL.ORDERSID
     *
     * @return the value of ORDERDETAIL.ORDERSID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public BigDecimal getOrdersid() {
        return ordersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERDETAIL.ORDERSID
     *
     * @param ordersid the value for ORDERDETAIL.ORDERSID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setOrdersid(BigDecimal ordersid) {
        this.ordersid = ordersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERDETAIL.ITEMSID
     *
     * @return the value of ORDERDETAIL.ITEMSID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public BigDecimal getItemsid() {
        return itemsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERDETAIL.ITEMSID
     *
     * @param itemsid the value for ORDERDETAIL.ITEMSID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setItemsid(BigDecimal itemsid) {
        this.itemsid = itemsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERDETAIL.ITEMSNUM
     *
     * @return the value of ORDERDETAIL.ITEMSNUM
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public BigDecimal getItemsnum() {
        return itemsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERDETAIL.ITEMSNUM
     *
     * @param itemsnum the value for ORDERDETAIL.ITEMSNUM
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setItemsnum(BigDecimal itemsnum) {
        this.itemsnum = itemsnum;
    }
}