package cn.itcast.zjw.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class OrderdetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public OrderdetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrdersidIsNull() {
            addCriterion("ORDERSID is null");
            return (Criteria) this;
        }

        public Criteria andOrdersidIsNotNull() {
            addCriterion("ORDERSID is not null");
            return (Criteria) this;
        }

        public Criteria andOrdersidEqualTo(BigDecimal value) {
            addCriterion("ORDERSID =", value, "ordersid");
            return (Criteria) this;
        }

        public Criteria andOrdersidNotEqualTo(BigDecimal value) {
            addCriterion("ORDERSID <>", value, "ordersid");
            return (Criteria) this;
        }

        public Criteria andOrdersidGreaterThan(BigDecimal value) {
            addCriterion("ORDERSID >", value, "ordersid");
            return (Criteria) this;
        }

        public Criteria andOrdersidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDERSID >=", value, "ordersid");
            return (Criteria) this;
        }

        public Criteria andOrdersidLessThan(BigDecimal value) {
            addCriterion("ORDERSID <", value, "ordersid");
            return (Criteria) this;
        }

        public Criteria andOrdersidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDERSID <=", value, "ordersid");
            return (Criteria) this;
        }

        public Criteria andOrdersidIn(List<BigDecimal> values) {
            addCriterion("ORDERSID in", values, "ordersid");
            return (Criteria) this;
        }

        public Criteria andOrdersidNotIn(List<BigDecimal> values) {
            addCriterion("ORDERSID not in", values, "ordersid");
            return (Criteria) this;
        }

        public Criteria andOrdersidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDERSID between", value1, value2, "ordersid");
            return (Criteria) this;
        }

        public Criteria andOrdersidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDERSID not between", value1, value2, "ordersid");
            return (Criteria) this;
        }

        public Criteria andItemsidIsNull() {
            addCriterion("ITEMSID is null");
            return (Criteria) this;
        }

        public Criteria andItemsidIsNotNull() {
            addCriterion("ITEMSID is not null");
            return (Criteria) this;
        }

        public Criteria andItemsidEqualTo(BigDecimal value) {
            addCriterion("ITEMSID =", value, "itemsid");
            return (Criteria) this;
        }

        public Criteria andItemsidNotEqualTo(BigDecimal value) {
            addCriterion("ITEMSID <>", value, "itemsid");
            return (Criteria) this;
        }

        public Criteria andItemsidGreaterThan(BigDecimal value) {
            addCriterion("ITEMSID >", value, "itemsid");
            return (Criteria) this;
        }

        public Criteria andItemsidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ITEMSID >=", value, "itemsid");
            return (Criteria) this;
        }

        public Criteria andItemsidLessThan(BigDecimal value) {
            addCriterion("ITEMSID <", value, "itemsid");
            return (Criteria) this;
        }

        public Criteria andItemsidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ITEMSID <=", value, "itemsid");
            return (Criteria) this;
        }

        public Criteria andItemsidIn(List<BigDecimal> values) {
            addCriterion("ITEMSID in", values, "itemsid");
            return (Criteria) this;
        }

        public Criteria andItemsidNotIn(List<BigDecimal> values) {
            addCriterion("ITEMSID not in", values, "itemsid");
            return (Criteria) this;
        }

        public Criteria andItemsidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ITEMSID between", value1, value2, "itemsid");
            return (Criteria) this;
        }

        public Criteria andItemsidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ITEMSID not between", value1, value2, "itemsid");
            return (Criteria) this;
        }

        public Criteria andItemsnumIsNull() {
            addCriterion("ITEMSNUM is null");
            return (Criteria) this;
        }

        public Criteria andItemsnumIsNotNull() {
            addCriterion("ITEMSNUM is not null");
            return (Criteria) this;
        }

        public Criteria andItemsnumEqualTo(BigDecimal value) {
            addCriterion("ITEMSNUM =", value, "itemsnum");
            return (Criteria) this;
        }

        public Criteria andItemsnumNotEqualTo(BigDecimal value) {
            addCriterion("ITEMSNUM <>", value, "itemsnum");
            return (Criteria) this;
        }

        public Criteria andItemsnumGreaterThan(BigDecimal value) {
            addCriterion("ITEMSNUM >", value, "itemsnum");
            return (Criteria) this;
        }

        public Criteria andItemsnumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ITEMSNUM >=", value, "itemsnum");
            return (Criteria) this;
        }

        public Criteria andItemsnumLessThan(BigDecimal value) {
            addCriterion("ITEMSNUM <", value, "itemsnum");
            return (Criteria) this;
        }

        public Criteria andItemsnumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ITEMSNUM <=", value, "itemsnum");
            return (Criteria) this;
        }

        public Criteria andItemsnumIn(List<BigDecimal> values) {
            addCriterion("ITEMSNUM in", values, "itemsnum");
            return (Criteria) this;
        }

        public Criteria andItemsnumNotIn(List<BigDecimal> values) {
            addCriterion("ITEMSNUM not in", values, "itemsnum");
            return (Criteria) this;
        }

        public Criteria andItemsnumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ITEMSNUM between", value1, value2, "itemsnum");
            return (Criteria) this;
        }

        public Criteria andItemsnumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ITEMSNUM not between", value1, value2, "itemsnum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated do_not_delete_during_merge Sat Feb 04 16:31:43 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ORDERDETAIL
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}