package cn.itcast.zjw.po;

import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.ID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.USERNAME
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.BIRTHDAY
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.SEX
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERS.ADDRESS
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.ID
     *
     * @return the value of USERS.ID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.ID
     *
     * @param id the value for USERS.ID
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.USERNAME
     *
     * @return the value of USERS.USERNAME
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.USERNAME
     *
     * @param username the value for USERS.USERNAME
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.BIRTHDAY
     *
     * @return the value of USERS.BIRTHDAY
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.BIRTHDAY
     *
     * @param birthday the value for USERS.BIRTHDAY
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.SEX
     *
     * @return the value of USERS.SEX
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.SEX
     *
     * @param sex the value for USERS.SEX
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERS.ADDRESS
     *
     * @return the value of USERS.ADDRESS
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERS.ADDRESS
     *
     * @param address the value for USERS.ADDRESS
     *
     * @mbggenerated Sat Feb 04 16:31:43 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}